### ISSUE TITLE
is this abandoned?

### ISSUE THREAD

**Issue by fballiano** [it4mage/CashOnDelivery#26]
I see unanswered issues and PRs, and the documentation still refers to msp/cashondelivery which was abandoned.

It this updated or should we consider another cashondelivery module?

**Comment by aleron75** [comment]
Hi Fabrizio,
the last commit dates back to 2018, I think this is not maintained anymore.

**Comment by fballiano** [comment]
there's no working FLOSS cash on delivery module for magento 2, it seems kinda crazy to me, it should be possible to open this repo to new people

**Comment by aleron75** [comment]
I agree, meanwhile, I invited you as a member.

**Comment by fballiano** [comment]
ok, thanks, i'm closing this cause I'll create new issues for other topics
